### ISSUE TITLE
.net unit test badge

### ISSUE THREAD

**Issue by daveboster** [daveboster/postman-load-testing#1]
Provide build and .net unit test badge in the readme file.

**Comment by daveboster** [comment]
## Adding DotNet Unit Test Badge
To create go to actions, selecting **Test dotnet** workflow, triple dots, selecting **Create status badge**.

❓What is “Event” selection for a badge? 
- According to GitHub [Adding a workflow status badge](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge) is allows you to filter the status based on events like **push**.

Adding unit tests to the continuous deployment workflow; in the original workflow, but missing.

The workflow using Windows image appears to take a lot longer than the Ubuntu image. Adding Windows to the original workflow using [matrix for workflow jobs](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs).

How Fascinating! ＼(๏◡๏)／ 
The same build process on Windows compared to Ubuntu is *4x* longer! 

![D461A2F3-1C6F-416E-982E-6D01161CAF30](https://user-images.githubusercontent.com/8752215/197346369-b3a92088-540c-43f6-ab3e-bef2bd19060e.jpeg)

❓Is it a wise use of resources to run these build processes on both Windows and Ubuntu for every commit or should we reserve Windows for PR’s into master or possibly only for releases?

**Comment by daveboster** [comment]
[Disabling and enabling a workflow](https://docs.github.com/en/actions/managing-workflow-runs/disabling-and-enabling-a-workflow) in GitHub.

Going to disable the Continuous Deployment workflow and move the publish to the workflow using the matrix.

**Comment by daveboster** [comment]
GitHub Workflow [Using conditions to control job execution](https://docs.github.com/en/actions/using-jobs/using-conditions-to-control-job-execution).

Syntax is different for jobs compared to steps.

``` yaml
name: example-workflow
on: [push]
jobs:
  production-deploy:
    if: github.repository == 'octo-org/octo-repo-prod'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
```

[Source:](https://github.com/grzegorzkrukowski/stackoverflow_tests/actions/runs/1988349309/workflow)

``` yaml 
jobs:
  test_job:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - name: Create flag
        id: create_flag
        run: |
          FLAG="true"
          echo "::set-output name=FLAG::$FLAG"
      - name: Run-me if FLAG is true
        if: ${{ steps.create_flag.outputs.FLAG == 'true' }}
        run: |
          echo "TRUE"
          # some logic to run if flag==true
      - name: Run-me if FLAG is false
        if: ${{ steps.create_flag.outputs.FLAG == 'false' }}
        run: |
          echo "FALSE"
          # some logic to run if flag==true
```
